update EFFECT_SYNCHRO_MATERIAL for レボリューション・シンクロン
Fluorohydride/ygopro-core pull request #491
Opened 2023-03-08 07:43 UTC by chronogenexx

update 1: add `Duel.GetSynchroMaterial`(get using synchro material).
update 2: rename `EFFECT_SYNCHRO_MATERIAL` to `EFFECT_EXTRA_SYNCHRO_MATERIAL`.
update 3: `EFFECT_EXTRA_SYNCHRO_MATERIAL` can check in hand.

2023-03-15 08:33 UTC, mercury233 requested changes

2023-03-15 08:33 UTC, mercury233 commented on card.cpp
> +			for(int32 i = 0; i < eset.size(); ++i)
missing `{}` ?

2023-03-15 10:50 UTC, chronogenexx commented on card.cpp
> +			for(int32 i = 0; i < eset.size(); ++i)
https://github.com/Fluorohydride/ygopro-core/pull/491/commits/a66c41285bde736c93debb1c7e5a2c0bf07ec71a fixed.

2023-03-20 02:18 UTC, mercury233 approved these changes

2023-03-20 07:55 UTC, merged