fix: summon in Chain Link 1
Fluorohydride/ygopro-core pull request #544
Opened 2024-01-28 12:16 UTC by salix5

@mercury233 
@purerosefallen 
fix https://github.com/Fluorohydride/ygopro-scripts/pull/2246

Before:
- EVENT_SPSUMMON_SUCCESS of summon in Chain Link 1 and EVENT_CHAIN_END are different timing.
(Break Auxiliary.RegisterMergedDelayedEvent)

After:
- They are the same timing.

2024-01-30 01:16 UTC, mercury233 requested changes

2024-01-30 01:16 UTC, mercury233 commented on operations.cpp
> +		if(!action_type) {
What is `action_type` ? Is it boolean?

2024-01-30 08:05 UTC, salix5 commented on operations.cpp
> +		if(!action_type) {
9022db8dc9192df5e5488e92c0d46f84a8ab867c
action type:
SUMMON_IN_MP (0)
Summon in Main Phase.
It should generate PROCESSOR_POINT_EVENT directly.

SUMMON_IN_CHAIN (1)
Summon in Chain Link.
It should wait EVENT_CHAIN_END.

2024-01-30 08:13 UTC, mercury233 commented on field.h
> +#define SUMMON_IN_MP	0
```suggestion
#define SUMMON_IN_IDLE	0
```

2024-01-31 01:21 UTC, merged

2024-01-31 10:42 UTC, mercury233 commented
The additional normal summon of _Fire Formation - Tenki_ can't trigger `EVENT_SUMMON_SUCCESS`

replay:
[summon success.zip](https://github.com/Fluorohydride/ygopro-core/files/14110538/summon.success.zip)

2024-01-31 11:41 UTC, salix5 commented
confirming